### ISSUE TITLE
How to calculate the average recall, precision and F1-score ?

### ISSUE THREAD

**Issue by AOTY-szy** [SHIDCenter/PathoNet#17]

**Comment by Farzin-Negahbani** [comment]
I am not sure if I completely understand your question or not, but all metrics are being calculated in the ["evaluation.py"](https://github.com/SHIDCenter/PathoNet/blob/master/evaluation.py). If it doesn't answer your question, would you please elaborate more?

**Comment by AOTY-szy** [comment]
> I am not sure if I completely understand your question or not, but all metrics are being calculated in the ["evaluation.py"](https://github.com/SHIDCenter/PathoNet/blob/master/evaluation.py). If it doesn't answer your question, would you please elaborate more?

Thanks for your reply. 
I found that the F1 scores of immunopositive, immunonegative, and lymphocyte cells are reported as 0.8523, 0.7815 and 0.379, respectively. The micro-F1 score should be (0.8523 +  0.7815 + 0.379) / 3 = 0.6709. So,  I wonder if the reported average F1 score (0.7928) in your paper means the micro-F1 ? 
Actually, I didn't found its calculation process in the 'evaluation.py' file.

**Comment by Farzin-Negahbani** [comment]
> > I am not sure if I completely understand your question or not, but all metrics are being calculated in the ["evaluation.py"](https://github.com/SHIDCenter/PathoNet/blob/master/evaluation.py). If it doesn't answer your question, would you please elaborate more?
> 
> Thanks for your reply. I found that the F1 scores of immunopositive, immunonegative, and lymphocyte cells are reported as 0.8523, 0.7815 and 0.379, respectively. The micro-F1 score should be (0.8523 + 0.7815 + 0.379) / 3 = 0.6709. So, I wonder if the reported average F1 score (0.7928) in your paper means the micro-F1 ? Actually, I didn't found its calculation process in the 'evaluation.py' file.

Thank you for the clarification. Since we are dealing with an unbalanced class count problem ( based on cell information table immunopositive: 50861, immunonegative: 107647, and lymphocyte: 4490), we report the weighted average of the F1-scores as the average F1-score.  So the math goes like:

(0.8523 * 50861 + 0.7815 * 107647+ 0.379 * 4490) / 162998 = 0.79

**Comment by AOTY-szy** [comment]
> > > I am not sure if I completely understand your question or not, but all metrics are being calculated in the ["evaluation.py"](https://github.com/SHIDCenter/PathoNet/blob/master/evaluation.py). If it doesn't answer your question, would you please elaborate more?
> > 
> > 
> > Thanks for your reply. I found that the F1 scores of immunopositive, immunonegative, and lymphocyte cells are reported as 0.8523, 0.7815 and 0.379, respectively. The micro-F1 score should be (0.8523 + 0.7815 + 0.379) / 3 = 0.6709. So, I wonder if the reported average F1 score (0.7928) in your paper means the micro-F1 ? Actually, I didn't found its calculation process in the 'evaluation.py' file.
> 
> Thank you for the clarification. Since we are dealing with an unbalanced class count problem ( based on cell information table immunopositive: 50861, immunonegative: 107647, and lymphocyte: 4490), we report the weighted average of the F1-scores as the average F1-score. So the math goes like:
> 
> (0.8523 * 50861 + 0.7815 * 107647+ 0.379 * 4490) / 162998 = 0.79

Thanks very much.
