### ISSUE TITLE
image en sortie non annotée 

### ISSUE THREAD

**Issue by Achraf97-lab** [SHIDCenter/PathoNet#2]
hello, I tried to run the demo.py code directly with an image size 256 * 256, I downloaded the pre-trained PathoNet.hdf5 model so I changed the name in the demo.json because pre-trainedModels defined as PathoNet.h5, I installed Keras == 2.4.3 tensorflow == 2.5.0 because the ones in requirments.txt don't work for me, but unfortunately the output image was not annotated

**Comment by Achraf97-lab** [comment]
> bonjour, j'ai essayé d'exécuter le code demo.py directement avec une taille d'image 256 * 256, j'ai téléchargé le modèle PathoNet.hdf5 pré-entraîné donc j'ai changé le nom dans le demo.json car les modèles pré-entraînés définis comme PathoNet.h5, J'ai installé Keras == 2.4.3 tensorflow == 2.5.0 car ceux de requirments.txt ne fonctionnent pas pour moi, mais malheureusement l'image de sortie n'a pas été annotée

**Comment by Achraf97-lab** [comment]
bonjour, j'ai essayé d'exécuter le code demo.py directement avec une taille d'image 256 * 256, j'ai téléchargé le modèle PathoNet.hdf5 pré-entraîné donc j'ai changé le nom dans le demo.json car les modèles pré-entraînés définis comme PathoNet.h5, J'ai installé Keras == 2.4.3 tensorflow == 2.5.0 car ceux de requirments.txt ne fonctionnent pas pour moi, mais malheureusement l'image de sortie n'a pas été annotée
quand je fais peint(pred) j'ai ca : [ ] je pense que y'a un problème de prediction

**Comment by Farzin-Negahbani** [comment]
@Achraf97-lab It's now fixed. Please pull the latest version of demo.py and pre-trained weights.

**Comment by Achraf97-lab** [comment]
Bonjour Farzin, ca marche merci beaucoup !
