### ISSUE TITLE
how to design the thresold value of perdict?

### ISSUE THREAD

**Issue by JiweiMaster** [SHIDCenter/PathoNet#4]
I want to applt this code to new dataset, but i don't know how to design the thresold values?

"thresholds": [
        120,
        180,
        40
]

**Comment by Farzin-Negahbani** [comment]
Hello @JiweiMaster, please refer to section A.5 of the paper's supplementary materials [here](https://static-content.springer.com/esm/art%3A10.1038%2Fs41598-021-86912-w/MediaObjects/41598_2021_86912_MOESM1_ESM.pdf). You can find the tuning approach and each model's threshold that we used in this work.
