### ISSUE TITLE
Report an error when doing a comparative experiment

### ISSUE THREAD

**Issue by JiweiMaster** [SHIDCenter/PathoNet#5]
when I edit the config file in PathoNet/configs/train.json
the "model": "PathoNet" ==> "model": "Deeplab_xception",
Training process will be report "TypeError: can't pickle module objects" after a epoch completed.

**Comment by Farzin-Negahbani** [comment]
@JiweiMaster it should be fixed now. Please pull the latest version and let me know if it's fixed.
