### ISSUE TITLE
How to get a dataset

### ISSUE THREAD

**Issue by xiongxuechun** [SHIDCenter/PathoNet#9]
Hi, i fill out the request from this URL https://shiraz-hidc.com/service/ki-67-dataset/ ,but i cannot download the SHIDC-B-Ki-67 dataset

**Comment by xiongxuechun** [comment]
> Hi, i fill out the request from this URL https://shiraz-hidc.com/service/ki-67-dataset/ ,but i cannot download the SHIDC-B-Ki-67 dataset

**Comment by Farzin-Negahbani** [comment]
@xiongxuechun Hi,
Based on our policy, we kindly asked your request to be re-submitted with full details of your affiliation and name (e.g. University and major). I've sent you two emails in this regard on November 4 and 10 but I didn't get any response. In case there is any further issue please reach me via my personal email can be found [here](https://shiraz-hidc.com/people/).
